Controllers/GameMappingController.cs
using BusinessLogic;
using BusinessLogic.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MVC_Demo.Enums;
using Newtonsoft.Json;

namespace MVC_Demo.Controllers
{
    public class GameMappingController : Controller
    {
        UserParameter UserList = new UserParameter();
        DeviceGameMappingModelVM ModelVM = new DeviceGameMappingModelVM();
        List<CommanEnum> commanEnum = new List<CommanEnum>();
        // GET: GameMappingController

        public override void OnActionExecuted(ActionExecutedContext context)
        {
            if (context != null)
            {
                var Data = HttpContext != null ? Convert.ToInt32(HttpContext.Session.GetInt32("UserId")) : 0;
                if (Data == 0)
                {
                    context.Result = new RedirectResult("/UserLogin/Login");
                }
            }
        }
        public ActionResult Index(string stringData)
        {
            if (stringData != "")
            {
                ViewBag.isSaved = stringData;
            }
            ModelVM.Op = 1;
            ModelVM.UserID = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
            var deviceGameMappingList = DeviceGameMappingDataAccess.GetDeviceMappingList(ModelVM);
            return View(deviceGameMappingList);
        }


        // GET: GameMappingController/Create
        public ActionResult CreateDeviceGameMapping(int id)
        {
            if (id != 0)
            {
                ModelVM.Op = 2;
                ModelVM.MappingID = id;
                var dbDeviceInfo = DeviceGameMappingDataAccess.GetDeviceMappingData(ModelVM);
                dbDeviceInfo.minute = dbDeviceInfo.GameTime.Minutes.ToString();
                dbDeviceInfo.Seconds = dbDeviceInfo.GameTime.Seconds.ToString();
                ViewBag.UserId = dbDeviceInfo.UserID;
                ViewBag.DeviceInfoData = dbDeviceInfo;
            }
            DeviceInfoModelVM device = new DeviceInfoModelVM();
            device.Op = 1;
            if (id == 0)
            {
                device.UserID = (int)HttpContext.Session.GetInt32("UserId");
            }
            else
            {
                device.UserID = ViewBag.UserId;
            }
            ViewBag.DeviceData = DeviceInfoDataAccess.GetDeviceInfoList(device).ToList();
            //GameMasterVM game = new GameMasterVM();
            dynamic dynamic = new System.Dynamic.ExpandoObject();
            dynamic.Op = 1;
            //dynamic.UserID = HttpContext.Session.GetInt32("UserId");
            if(id !=0)
            {
                dynamic.UserID= ViewBag.UserId;
                dynamic.Op = 7;
            }
            ViewBag.GameData = GameDataAccess.GetGameList(dynamic);
            UserList.op = 5;
            //UserList.UserID = id;
            UserList.InActiveDate = DateTime.Now;
            ViewBag.UserData = DataAccess.GetList(UserList);
            //ViewBag.GameData = GameDataAccess.GetGameList(game).Where(p => p.InActiveDate != null).ToList();
            for (int i = 0; i < 60; i++)
            {
                CommanEnum minutes = new CommanEnum();
                minutes.minute = i.ToString();
                minutes.minuteVlaue = i.ToString();
                commanEnum.Add(minutes);
            }
            ViewBag.MinuteData = commanEnum.ToList();
            ViewBag.SecondData = commanEnum.ToList();
            return View();
        }

        // POST: GameMappingController/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]  

        //public ActionResult CreateDeviceGameMapping(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        var time = "00:" + collection["ddlMinuteId"].ToString() + ":" + collection["ddlSecondId"].ToString();
        //        var cTime = TimeSpan.Parse(time);
        //        if (id == 0)
        //        {                   
        //            ModelVM.Op = 3;
        //            ModelVM.DeviceID = Convert.ToInt32(collection["ddlDeviceId"].ToString());
        //            ModelVM.GameID = Convert.ToInt32(collection["ddlGameId"].ToString());
        //            ModelVM.GameTime = cTime;
        //            ModelVM.GameAmount = Convert.ToDecimal(collection["gameAmount"].ToString());
        //            var deviceData = DeviceGameMappingDataAccess.CRUDDeviceMapping(ModelVM);
        //            return RedirectToAction(nameof(Index));
        //        }
        //        else
        //        {                   
        //            ModelVM.Op = 2;
        //            ModelVM.MappingID = id;
        //            var Models = DeviceGameMappingDataAccess.GetDeviceMappingData(ModelVM);
        //            //ModelVM.MappingID = Models.GameID;
        //            //ModelVM.MappingID = id;
        //            ModelVM.Op = 4;
        //            ModelVM.DeviceID = Convert.ToInt32(collection["ddlDeviceId"]);
        //            ModelVM.GameID = Convert.ToInt32(collection["ddlGameId"].ToString());
        //            ModelVM.GameTime = cTime;
        //            ModelVM.GameAmount = Convert.ToDecimal(collection["gameAmount"].ToString());
        //            var deviceData = DeviceGameMappingDataAccess.CRUDDeviceMapping(ModelVM);
        //            return RedirectToAction(nameof(Index));
        //        }
        //    }
        //    catch(Exception ex)
        //    {
        //        return View();
        //    }
        //}

        // GET: GameMappingController/Edit/

        // GET: GameMappingController/Delete/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateDeviceGameMapping(int id, IFormCollection collection)
        {
            try
            {
                var time = "00:" + collection["ddlMinuteId"].ToString() + ":" + collection["ddlSecondId"].ToString();
                var cTime = TimeSpan.Parse(time);
                //if (Convert.ToInt32(collection["deviceID"]) == 0)
                if(id == 0)
                {
                    ModelVM.Op = 3;
                    ModelVM.DeviceID = Convert.ToInt32(collection["ddlDeviceId"].ToString());
                    ModelVM.GameID = Convert.ToInt32(collection["ddlGameId"].ToString());
                    ModelVM.GameTime = cTime;
                    ModelVM.GameAmount = Convert.ToDecimal(collection["gameAmount"].ToString());
                    var deviceData = DeviceGameMappingDataAccess.CRUDDeviceMapping(ModelVM);
                    return RedirectToAction(nameof(Index), new { stringData = deviceData.UpdateData });
                }
                else
                {
                    ModelVM.Op = 2;
                    ModelVM.MappingID = id;
                    //var Models = DeviceGameMappingDataAccess.GetDeviceMappingData(ModelVM);
                    //ModelVM.MappingID = Models.GameID;
                    ModelVM.Op = 4;
                    ModelVM.DeviceID = Convert.ToInt32(collection["ddlDeviceId"].ToString());
                    ModelVM.GameID = Convert.ToInt32(collection["ddlGameId"].ToString());
                    ModelVM.GameTime = cTime;
                    ModelVM.GameAmount = Convert.ToDecimal(collection["gameAmount"].ToString());
                    var deviceData = DeviceGameMappingDataAccess.CRUDDeviceMapping(ModelVM);
                    return RedirectToAction(nameof(Index), new { stringData = deviceData.UpdateData });
                }
            }
            catch (Exception ex)
            {
                
                return View();
            }
        }
        public JsonResult Delete(int id, int ischecked)
        {
            ModelVM.MappingID = id;
            ModelVM.IsCheckActive = ischecked;
            ModelVM.Op = 5;
            var userModel = DeviceGameMappingDataAccess.CRUDDeviceMapping(ModelVM);
            return Json("");
        }

        [HttpGet]
        public JsonResult GetDevices(string UserId)
        {
            DeviceGameMappingCls deviceGameMappingCls = new DeviceGameMappingCls();

            dynamic dynamic = new System.Dynamic.ExpandoObject();
            dynamic.Op = 1;
            dynamic.UserId = UserId;
            deviceGameMappingCls.deviceInfoModels = DeviceInfoDataAccess.GetDeviceInfoLists(dynamic);

            dynamic.Op = 7;
            dynamic.UserId = UserId;
            deviceGameMappingCls.gameMasters = GameDataAccess.GetGameLists(dynamic);
            return Json(JsonConvert.SerializeObject(deviceGameMappingCls));
        }

        //[HttpGet]
        //public JsonResult GetGames(string UserId)
        //{
        //    dynamic dynamic = new System.Dynamic.ExpandoObject();
        //    dynamic.Op = 7;
        //    dynamic.UserId = UserId;
        //    return Json(GameDataAccess.GetGameLists(dynamic));
    }
}

public class DeviceGameMappingCls
{
    public List<DeviceInfoModel> deviceInfoModels;
    public List<GameMaster> gameMasters;
}

Views/GameMapping/CreateDeviceGameMapping.cshtml
@using Microsoft.AspNetCore.Http;
@{
    Layout = "_Layout";
    ViewData["Title"] = "Devcie Location Create Page";
    var DeviceData = (BusinessLogic.Models.DeviceGameMappingModel)ViewBag.DeviceInfoData;
    var DeviceInfoData = (List<BusinessLogic.Models.DeviceInfoModel>)ViewBag.DeviceData;
    var GameData = (List<BusinessLogic.Models.GameMaster>)ViewBag.GameData;
    var MinuteData = (List<MVC_Demo.Enums.CommanEnum>)ViewBag.MinuteData;
    var SecondData = (List<MVC_Demo.Enums.CommanEnum>)ViewBag.SecondData;
    var UserData = (List<BusinessLogic.Models.UserModel>)ViewBag.UserData;
}
<div class="wrapper ">

    <div class="main-panel">
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header card-header-blue card-header-icon">
                                <div class="row">
                                    <div class="col-lg-10">
                                        <div class="card-icon">
                                            <i class="material-icons">devices</i>
                                        </div>
                                        <h4 class="card-title">@ViewData["Title"]</h4>
                                    </div>
                                    <div class="col-lg-2">
                                        <a class="btn btn-bluedark float-right btn-sm" href="/GameMapping/Index"><i class="material-icons">remove_red_eye</i>View Device</a>
                                    </div>
                                </div>
                            </div>
                            @using (Html.BeginForm("CreateDeviceGameMapping", "GameMapping", FormMethod.Post))
                            {
                                <div class="card-body row">
                                    @{ if (Convert.ToInt32(Context.Session.GetInt32("UserRoleID")) == 1)
                                        {
                                            <div class="col-lg-12">
                                                <div class="form-group">
                                                    @*<label for="ddlLocationId" class="bmd-label-floating"> Device Name * </label>*@
                                                    <select class="form-control selectpicker clsuserlist" data-style="select-with-transition" id="userlist" name="userlist" required="true">
                                                        <option value="0" selected="">Select User</option>
                                                        @foreach (var use in UserData)
                                                        {
                                                            <option value="@(use.UserID)" selected="@(ViewBag.UserId != null ? (ViewBag.UserId.ToString() == use.UserID.ToString() ? true : false):false)">@use.UserName</option>
                                                        }
                                                    </select>
                                                </div>
                                            </div>
                                        }
                                    }

                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            @*<label for="ddlLocationId" class="bmd-label-floating"> Device Name * </label>*@
                                            <select class="form-control selectpicker" data-style="select-with-transition" id="ddlDeviceId" name="ddlDeviceId" required="true">
                                                <option value="0" selected="">Select Device Name</option>
                                                @foreach (var location in DeviceInfoData)
                                                {
                                                    <option value="@location.DeviceID" selected="@(DeviceData != null ? (DeviceData.DeviceID == location.DeviceID ? true : false) : false)">@location.DeviceName</option>
                                                }
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            @*<label for="ddlLocationId" class="bmd-label-floating"> Game Name * </label>*@
                                            <select class="form-control selectpicker" data-style="select-with-transition" id="ddlGameId" name="ddlGameId" required="true">
                                                <option value="0" selected="">Select Game Name</option>
                                                @foreach (var location in GameData)
                                                {
                                                    <option value="@location.GameID" selected="@(DeviceData != null ? (DeviceData.GameID == location.GameID ? true : false) : false)">@location.GameName</option>
                                                }
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            @*<label for="ddlLocationId" class="bmd-label-floating w-100"> Game Time * </label>*@
                                            <select class="form-control selectpicker w-25" data-style="select-with-transition" id="ddlMinuteId" name="ddlMinuteId" required="true">
                                                <option value="0" selected="">Select Minute</option>
                                                @foreach (var min in MinuteData)
                                                {
                                                    <option value="@min.minuteVlaue" selected="@(DeviceData != null ? (DeviceData.minute == min.minuteVlaue ? true: false):false)">@min.minute</option>
                                                }
                                            </select>
                                            <select class="form-control selectpicker w-25" data-style="select-with-transition" id="ddlSecondId" name="ddlSecondId" required="true">
                                                <option value="0" selected="">Select Second</option>
                                                @foreach (var sec in SecondData)
                                                {
                                                    <option value="@sec.minuteVlaue" selected="@(DeviceData != null ? (DeviceData.Seconds == sec.minuteVlaue ? true: false):false)">@sec.minute</option>
                                                }
                                            </select>
                                            @*<select class="form-control selectpicker w-25" data-style="select-with-transition" id="ddlSecondId" name="ddlSecondId" required="true">
                                                    <option value="0" selected="">Select User</option>
                                                    @foreach (var use in UserData)
                                                    {
                                                        <option value="@use.UserID">@use.UserID</option>
                                                    }
                                                </select>*@
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label for="dviceAddress" class="bmd-label-floating">Game Amount *</label>
                                            <input type="text" class="form-control" id="gameAmount" value="@(DeviceData != null ? (DeviceData.GameAmount == 0 ? ' ': DeviceData.GameAmount):' ')" required="true" name="gameAmount">
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer text-right">
                                    <input type="hidden" name="deviceID" value="@(DeviceData != null ? (DeviceData.DeviceID == 0 ? 0: DeviceData.DeviceID):0)" />
                                    <button type="submit" class="btn btn-bluedark">Save</button>
                                </div>
                            }
                            <!-- end content-->
                        </div>
                        <!--  end card  -->
                    </div>
                    <!-- end col-md-12 -->
                </div>
                <!-- end row -->
            </div>
        </div>

    </div>
</div>
<script src="~/assets/js/core/jquery.min.js"></script>
<script type="text/javascript">
    $(".clsuserlist").off('change').on('change',function () {
        var userId = $('#userlist').val();

        $.ajax({
            url: '/GameMapping/GetDevices',
            type: 'GET',
            datatype: 'json',
            contentType: 'application/json',
            data: { userId: userId },
            success: function (result)
            {
                debugger;
                var object = JSON.parse(result);
                var deviceInfoModels = object.deviceInfoModels;
                var gameMasters = object.gameMasters;

                $('#ddlDeviceId').html('');
                $('#ddlDeviceId').append($('<option></option>').val(0).html("Select Device"));
                $.each(deviceInfoModels, function (i, item)
                { 
                    $('#ddlDeviceId').append($('<option></option>').val(item.DeviceID).html(item.DeviceName));
                    $("#ddlDeviceId").selectpicker('refresh');

                });
               
                $('#ddlGameId').html('');
                $('#ddlGameId').append($('<option></option>').val(0).html("Select Game"));
                $.each(gameMasters, function (i, item)
                {
                    $('#ddlGameId').append($('<option></option>').val(item.GameID).html(item.GameName));
                    $("#ddlGameId").selectpicker('refresh');
                });
            }
        });
    });
    //$('#ddlGameId').on("change", function ()
    //{
    //    var dataid = $("#ddlGameId option:selected").attr('value');
    //    alert(dataid)
    //});
</script>

Views/GameMapping/Index.cshtml
@model List<BusinessLogic.Models.DeviceGameMappingModel>
@{
    Layout = "_Layout";
    ViewData["Title"] = "Device Game Mapping";
    var modalPopup = ViewBag.isSaved;
}
<div class="wrapper ">
    <div class="main-panel">
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header card-header-blue card-header-icon">
                                <div class="row">
                                    <div class="col-lg-10">
                                        <div class="card-icon">
                                            <i class="material-icons">place</i>
                                        </div>
                                        <h4 class="card-title">@ViewData["Title"]</h4>
                                    </div>
                                    <div class="col-lg-2">
                                        <a class="btn btn-bluedark float-right btn-sm" href="/GameMapping/CreateDeviceGameMapping"><i class="material-icons">add</i>Add Game Mapping</a>
                                    </div>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="toolbar">
                                    <!--        Here you can write extra buttons/actions for the toolbar              -->
                                </div>
                                <div class="material-datatables success">
                                    <table id="datatables" class="table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
                                        <thead>
                                            <tr>
                                                <th>Device Name</th>
                                                <th>Game Name</th>
                                                <th>Game timeing</th>
                                                <th>Game Amount</th>
                                                <th>Active Game</th>
                                                <th class="disabled-sorting text-right">Actions</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @{
                                                foreach (var DL in Model)
                                                {
                                                    <tr>
                                                        <td>@DL.DeviceName</td>
                                                        <td>@DL.GameName</td>
                                                        <td>@DL.GameTime</td>
                                                        <td>@DL.GameAmount</td>
                                                        <td>
                                                            <div class="togglebutton togglebutton-bluedark">
                                                                <label>
                                                                    <input type="checkbox" class="chkInActive" value="@DL.MappingID" checked="@(DL.ActiveDeviceInfo==true? true:false)">
                                                                    <span class="toggle"></span>
                                                                </label>
                                                            </div>
                                                        </td>
                                                        <td class="text-right flex-row">
                                                            <a href="/GameMapping/CreateDeviceGameMapping/@DL.MappingID" class="btn btn-link btn-info btn-just-icon"><i class="material-icons">edit</i></a>
                                                            @*<a href="Game/Delete/@gm.GameID" class="btn btn-link btn-danger btn-just-icon"><i class="material-icons">close</i></a>*@
                                                        </td>
                                                    </tr>
                                                }
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <!-- end content-->
                        </div>
                        <!--  end card  -->
                    </div>
                    <!-- end col-md-12 -->
                    <input type="hidden" id="lblPopup" value="@modalPopup" />
                </div>

                <!-- end row -->
            </div>
        </div>
    </div>
</div>
<script src="~/assets/js/core/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $('#datatables').DataTable({
            "pagingType": "full_numbers",
            "lengthMenu": [
                [10, 25, 50, -1],
                [10, 25, 50, "All"]
            ],
            "responsive": true,
            "language": {
                search: "INPUT",
                searchPlaceholder: "Search records",
            }
        });
        $(".pagination").addClass("pagination-bluedark");
        var table = $('#datatables').DataTable();

        // Edit record

        table.on('click', '.chkInActive', function () {
            debugger
            var id = $(this).val();
            var ischecked = ($(this).prop('checked') == true ? 1 : 0);
            var param = [];
            param.push({ name: 'id', value: id });
            param.push({ name: 'ischecked', value: ischecked });
            doAjaxSubmit("/GameMapping/Delete", param, function (json, action, success) {
                if (success) { }
            });
        });
        if ($("#lblPopup").val() == "Saved") {
            Swal.fire('Successfully', 'Game has been saved successfully!', 'success')
        }
        else if ($("#lblPopup").val() == "Updated") {
            Swal.fire('Successfully', 'Game Updated successfully!', 'success')
        }

        $("#datatables_filter").css({ "float": "right" });
        $("#datatables_paginate").css({ "float": "right" });

    });
</script>