Controllers/UserLoginController.cs
using BusinessLogic;
using BusinessLogic.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_Demo.Controllers
{
    public class UserLoginController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }

        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(IFormCollection collection)
        {
            UserParameter user = new UserParameter();
            if (Convert.ToString(collection["RegDevice"]).Length > 0)
            {
                dynamic dynamic = new System.Dynamic.ExpandoObject();
                dynamic.UserName = collection["RegUserName"].ToString();
                dynamic.FirstName = collection["RegFirstName"].ToString();
                dynamic.LastName = collection["RegLastName"].ToString();
                dynamic.Address = collection["RegAddress"].ToString();
                dynamic.Password = collection["RegPassword"].ToString();
                dynamic.DeviceCode = collection["RegDevice"].ToString();

                var userData = (UserModel)DataAccess.RegisterUseWithDevice(dynamic);
                if (userData == null)
                {
                    TempData["Error"] = "Device Code is not matched with system. ";
                    return View();
                }
                else
                {
                    user.UserName = collection["RegUserName"].ToString();
                    user.Password = collection["RegPassword"].ToString();
                }
            }
            else
            {
                user.UserName = collection["userName"].ToString();
                user.Password = collection["userPassword"].ToString();

            }
            //user.UserName = collection["userName"].ToString();
            //user.Password = collection["userPassword"].ToString();
            user.op = 6;
            var usersData = DataAccess.GetList(user).FirstOrDefault();
            if (usersData != null)
            {
                HttpContext.Session.SetString("UserName", usersData.UserName);
                HttpContext.Session.SetInt32("UserId", usersData.UserID);
                HttpContext.Session.SetString("UserFullName", usersData.FirstName + usersData.LastName);
                HttpContext.Session.SetString("UserRole", usersData.RoleName);
                HttpContext.Session.SetInt32("UserRoleID", usersData.UserRole);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                TempData["Error"] = "please insert correct User Name or Password ";
                return View();
            }
        }
    }
}

Views/UserLogin/Login - Copy.cshtml
@{
    var error = TempData["Error"];
}
<!DOCTYPE html>
<html lang="en">
<meta http-equiv="content-type" content="text/html;charset=utf-8" />
<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="../../assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="../../assets/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>
        MVCDemo
    </title>
    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="~/assets/css/font-awesome.min.css">
    <!-- CSS Files -->
    <link href="~/assets/css/material-dashboard.min6c54.css?v=2.2.2" rel="stylesheet" />
    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link href="~/assets/demo/demo.css" rel="stylesheet" />

</head>

<body class="off-canvas-sidebar">
    <div class="wrapper wrapper-full-page">
        <div class="page-header login-page header-filter" filter-color="black" style="background-image: url('../../assets/img/login.jpg'); background-size: cover; background-position: top center;">
            <!--   you can change the color of the filter page using: data-color="blue | purple | green | orange | red | rose " -->
            <div class="container">
                <div class="row">
                    <div class="col-lg-4 col-md-6 col-sm-8 ml-auto mr-auto">
                        @*<form class="form" method="" action="#">*@
                        <div class="card card-login card-hidden">

                            <input type="hidden" id="hdnError" value="@error" />
                            @using (Html.BeginForm("Login", "UserLogin", FormMethod.Post))
                            {
                                <div id="dvSignIn">
                                    <div class="card-header card-header-rose text-center">
                                        <h4 class="card-title">Login</h4>
                                    </div>
                                    <div class="card-body">
                                        @*<p class="card-description text-center">Or Be Classical</p>*@
                                        <div class="bmd-form-group">
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text">
                                                        <i class="material-icons">person</i>
                                                    </span>
                                                </div>
                                                <input type="text" class="form-control" name="userName" placeholder="User Name...">
                                            </div>
                                        </div>
                                        <div class="bmd-form-group">
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text">
                                                        <i class="material-icons">lock_outline</i>
                                                    </span>
                                                </div>
                                                <input type="password" class="form-control" name="userPassword" placeholder="Password...">
                                            </div>
                                        </div>

                                        <div class="card-footer justify-content-center">
                                            <a href="#" class="btn btn-rose btn-link btn-lg" id="btnLogin">Lets Go</a> / <a href="#" class="btn btn-rose btn-link btn-lg" onclick="return Register(1);">Register</a>
                                        </div>
                                    </div>
                                </div>

                                <!--<div id="dvSignUp" style="display:none">
                                    <div class="card-header card-header-rose text-center">
                                        <h4 class="card-title">Register</h4>
                                    </div>
                                    <div class="card-body">-->
                                        @*<p class="card-description text-center">Or Be Classical</p>*@
                                        <!--<div class="bmd-form-group">
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text">
                                                        <i class="material-icons">person</i>
                                                    </span>
                                                </div>
                                                <input type="text" class="form-control" name="userName" placeholder="User Name...">
                                            </div>
                                        </div>
                                        <div class="bmd-form-group">
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text">
                                                        <i class="material-icons">person</i>
                                                    </span>
                                                </div>
                                                <input type="text" class="form-control" name="first" placeholder="First Name...">
                                            </div>
                                        </div>
                                        <div class="bmd-form-group">
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text">
                                                        <i class="material-icons">person</i>
                                                    </span>
                                                </div>
                                                <input type="text" class="form-control" name="lastName" placeholder="Last Name...">
                                            </div>
                                        </div>
                                        <div class="bmd-form-group">
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text">
                                                        <i class="material-icons">home</i>
                                                    </span>
                                                </div>
                                                <input type="text" multiple class="form-control" name="userName" placeholder="Address...">
                                            </div>
                                        </div>
                                        <div class="bmd-form-group">
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text">
                                                        <i class="material-icons">lock_outline</i>
                                                    </span>
                                                </div>
                                                <input type="password" class="form-control" name="userPassword" placeholder="Password...">
                                            </div>
                                        </div>
                                        <div class="bmd-form-group">
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text">
                                                        <i class="material-icons">important_devices</i>
                                                    </span>
                                                </div>
                                                <input type="text" class="form-control" name="device" placeholder="Device Code...">
                                            </div>
                                        </div>

                                        <div class="card-footer justify-content-center">
                                            <a href="#" class="btn btn-rose btn-link btn-lg" id="btnRegister">Lets Go</a> / <a href="#" class="btn btn-rose btn-link btn-lg"  onclick="return Register(0);">Back</a>
                                        </div>
                                    </div>
                                </div>-->
                            }


                        </div>
                        @*</form>*@
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--   Core JS Files   -->
    <script src="~/assets/js/core/jquery.min.js"></script>
    <script src="~/assets/js/core/popper.min.js"></script>
    <script src="~/assets/js/core/bootstrap-material-design.min.js"></script>
    <script src="~/assets/js/plugins/perfect-scrollbar.jquery.min.js"></script>
    <!--  Notifications Plugin    -->
    <script src="~/assets/js/plugins/bootstrap-notify.js"></script>
    <!-- Sharrre libray -->
    <script src="~/assets/demo/jquery.sharrre.js"></script>

    <script>
        $(document).ready(function () {
            //  md.checkFullPageBackgroundImage();
            setTimeout(function () {
                // after 1000 ms we add the class animated to the login/register card
                $('.card').removeClass('card-hidden');
            }, 700);
            $("#btnLogin").on("click", function () {
                $(this).parent("div").parent("form").submit();
            });

            $("#btnRegister").on("click", function () {
                debugger;
                $.post('UserLogin/Register', data, function (responseData) {
                    //callback function
                });
            });

            if ($("#hdnError").val() != "") {
                $.notify($("#hdnError").val(), {
                    type: 'danger',
                    allow_dismiss: false,
                });
            }
        });

        function Register(val) {
            if (val == 0) { $("#dvSignIn").show(); $("#dvSignUp").hide(); }
            else { $("#dvSignIn").hide(); $("#dvSignUp").show();}
            return false;
        }

    </script>

</body>
</html>

Views/UserLogin/Login.cshtml
@{
    var error = TempData["Error"];
}

<!DOCTYPE html>
<html lang="en">
<meta http-equiv="content-type" content="text/html;charset=utf-8" />
<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="../../assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="../../assets/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>
        MVCDemo
    </title>
    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="~/assets/css/font-awesome.min.css">
    <!-- CSS Files -->
    <link href="~/assets/css/material-dashboard.min6c54.css?v=2.2.2" rel="stylesheet" />
    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link href="~/assets/demo/demo.css" rel="stylesheet" />

</head>

<body class="off-canvas-sidebar">
    <div class="wrapper wrapper-full-page">
        <div class="page-header login-page header-filter" filter-color="black" style="background-image: url('../../assets/img/login.jpg'); background-size: cover; background-position: top center;">
            <!--   you can change the color of the filter page using: data-color="blue | purple | green | orange | red | rose " -->
            <div class="container">
                <div class="row">
                    <div class="col-lg-4 col-md-6 col-sm-8 ml-auto mr-auto">
                        @*<form class="form" method="" action="#">*@
                        <div class="card card-login card-hidden">

                            <input type="hidden" id="hdnError" value="@error" />
                            @using (Html.BeginForm("Login", "UserLogin", FormMethod.Post))
                            {
                                <div id="dvSignIn">
                                    <div class="card-header card-header-rose text-center">
                                        <h4 class="card-title">Login</h4>
                                    </div>
                                    <div class="card-body">
                                        @*<p class="card-description text-center">Or Be Classical</p>*@
                                        <div class="bmd-form-group">
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text">
                                                        <i class="material-icons">person</i>
                                                    </span>
                                                </div>
                                                <input type="text" class="form-control" name="userName" placeholder="User Name...">
                                            </div>
                                        </div>
                                        <div class="bmd-form-group">
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text">
                                                        <i class="material-icons">lock_outline</i>
                                                    </span>
                                                </div>
                                                <input type="password" class="form-control" name="userPassword" placeholder="Password...">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card-footer justify-content-center">
                                        <a href="#" class="btn btn-rose btn-link btn-lg" id="btnLogin">Lets Go</a> / <a href="#" class="btn btn-rose btn-link btn-lg" onclick="Register(1);">Register</a>
                                    </div>
                                </div>


                                <div id="dvSignUp" style="display:none">
                                    <div class="card-header card-header-rose text-center">
                                        <h4 class="card-title">Register</h4>
                                    </div>
                                    <div class="card-body">
                                        <div class="bmd-form-group">
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text">
                                                        <i class="material-icons">person</i>
                                                    </span>
                                                </div>
                                                <input type="text" class="form-control" name="RegUserName" placeholder="User Name...">
                                            </div>
                                        </div>
                                        <div class="bmd-form-group">
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text">
                                                        <i class="material-icons">person</i>
                                                    </span>
                                                </div>
                                                <input type="text" class="form-control" name="RegFirstName" placeholder="First Name...">
                                            </div>
                                        </div>
                                        <div class="bmd-form-group">
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text">
                                                        <i class="material-icons">person</i>
                                                    </span>
                                                </div>
                                                <input type="text" class="form-control" name="RegLastName" placeholder="Last Name...">
                                            </div>
                                        </div>
                                        <div class="bmd-form-group">
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text">
                                                        <i class="material-icons">home</i>
                                                    </span>
                                                </div>
                                                <input type="text" multiple class="form-control" name="RegAddress" placeholder="Address...">
                                            </div>
                                        </div>
                                        <div class="bmd-form-group">
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text">
                                                        <i class="material-icons">lock_outline</i>
                                                    </span>
                                                </div>
                                                <input type="password" class="form-control" name="RegPassword" placeholder="Password...">
                                            </div>
                                        </div>
                                        <div class="bmd-form-group">
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text">
                                                        <i class="material-icons">important_devices</i>
                                                    </span>
                                                </div>
                                                <input type="text" class="form-control" name="RegDevice" placeholder="Device Code...">
                                            </div>
                                        </div>
                                    </div>

                                    <div class="card-footer justify-content-center">
                                        <a href="#" class="btn btn-rose btn-link btn-lg" id="btnRegister">Lets Go</a> / <a href="#" class="btn btn-rose btn-link btn-lg" onclick="return Register(0);">Back</a>
                                    </div>
                                </div>
                            }
                        </div>
                        @*</form>*@
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--   Core JS Files   -->
    <script src="~/assets/js/core/jquery.min.js"></script>
    <script src="~/assets/js/core/popper.min.js"></script>
    <script src="~/assets/js/core/bootstrap-material-design.min.js"></script>
    <script src="~/assets/js/plugins/perfect-scrollbar.jquery.min.js"></script>
    <!--  Notifications Plugin    -->
    <script src="~/assets/js/plugins/bootstrap-notify.js"></script>
    <!-- Sharrre libray -->
    <script src="~/assets/demo/jquery.sharrre.js"></script>

    <script>
        $(document).ready(function () {
            //  md.checkFullPageBackgroundImage();
            setTimeout(function () {
                // after 1000 ms we add the class animated to the login/register card
                $('.card').removeClass('card-hidden');
            }, 700);
            $("#btnLogin").on("click", function () {
                //$(this).parent("div").parent("form").submit();
                $(this).parent("div").parent("div").parent("form").submit();
            });
            $("#btnRegister").on("click", function () {
                //$(this).parent("div").parent("form").submit();
                $(this).parent("div").parent("div").parent("form").submit();
            });
            if ($("#hdnError").val() != "") {
                $.notify($("#hdnError").val(), {
                    type: 'danger',
                    allow_dismiss: false,
                });
            }
        });

        function Register(val) {
            if (val == 0) { $("#dvSignIn").show(); $("#dvSignUp").hide(); }
            else { $("#dvSignIn").hide(); $("#dvSignUp").show(); }
        }

    </script>

</body>
</html>